language: objective-c

before_install:
  - Frameworks/gethamcrest
  - sudo easy_install cpp-coveralls

script:
  - xctool test -project Source/OCMockito.xcodeproj -scheme OCMockito -sdk macosx10.9
  - xctool test -project Source/OCMockito.xcodeproj -scheme libocmockito -sdk iphonesimulator8.1 -destination "platform=iOS Simulator,name=iPhone 5,OS=8.1"
  - xctool test -project Source/OCMockito.xcodeproj -scheme libocmockito -sdk iphonesimulator8.1 -destination "platform=iOS Simulator,name=iPhone 5s,OS=8.1"

after_success:
  - ./Cocoanetics-Ruby/coveralls.rb --exclude-folder Source/Tests --exclude-folder Source/ThirdParty --exclude-folder Frameworks --exclude-folder Examples
