language: objective-c
osx_image: xcode11

before_install:
  - Frameworks/gethamcrest
  - gem install slather

script:
  - set -o pipefail;
  - xcodebuild test -project Source/OCMockito.xcodeproj -scheme OCMockito -sdk macosx | xcpretty
  - xcodebuild test -project Source/OCMockito.xcodeproj -scheme libocmockito -sdk iphonesimulator -destination "platform=iOS Simulator,OS=latest,name=iPhone 5" | xcpretty
  - xcodebuild test -project Source/OCMockito.xcodeproj -scheme libocmockito -sdk iphonesimulator -destination "platform=iOS Simulator,OS=latest,name=iPhone 5s" | xcpretty
  - pod spec lint --quick

after_success:
  - slather
